### ISSUE TITLE
Technology facet requests failing

### ISSUE THREAD

**Issue by BeckerJoe** [leonawicz/eia#25]
Hey there,

I'm not sure if I'm missing something, but the "technology" facet seems to not be functional for calling eia_data. I am trying to get hydropower facilities in New England using this package, but whenever I try specifying the "technology" facet I get the following error.

Error in curl::curl_fetch_memory(url, handle = handle): URL using bad/illegal format or missing URL [api.eia.gov]
Request failed [ERROR]. Retrying in 1.1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): URL using bad/illegal format or missing URL [api.eia.gov]
Request failed [ERROR]. Retrying in 2.8 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL [api.eia.gov]

From what I can tell from reading the documentation, I think I have the facets parameter set up correctly. For context, I have also tried this out of loop to test all possible sources of error, and I've narrowed what I believe to be the source of the issue to the technology facet.

Any advice would be appreciated.

Code:

`library(eia)
library(tidyverse)

# Getting metadata for the two datasets that I am interested in 
hydropower_meta <- eia_metadata("electricity/operating-generator-capacity")
energy_meta <- eia_metadata("electricity/facility-fuel")

# Here I tried getting the facet names and filtering by those containing Hydro in case I was making a typo somewhere
tech_facets <- eia_facets("electricity/operating-generator-capacity", "technology") %>% 
  filter(grepl("Hydro", id) == T)

NE.states.abs <- c("NH", "CT", "MA", "ME", "RI", "VT")
iter <- expand_grid(NE.states.abs, tech_facets)

# Should loop through and pull data for each state and technology
eia_hydropower <- purrr::map(1:nrow(iter), \(x){
  eia_data(
    dir = "electricity/operating-generator-capacity",
    data = c("nameplate-capacity-mw", "operating-year-month"),
    facets = list(stateid = iter[[x,1]], technology = iter[[x,2]])
  )
}) %>% 
  bind_rows()`

**Comment by BeckerJoe** [comment]
I think I've figure out the issue: the spaces in the facet names are tripping up the data pull. Tested this using GET() with the request URL (this also was failing with the same issue before) after replacing spaces with "%20" and it worked. I have forked and am attempting to find a fix and initiate a pull request (this is my first time doing so).

**Comment by mghoff** [comment]
Hey @BeckerJoe , 

I can confirm you've identified the problem. I have a fix in place and will push up to the `dev` branch this afternoon ET. Unfortunately, I don't think it solves your entire issue as many of the States return no data for `*Hydro*` facets. You can either continue with your fork or, what I recommend in the meantime would be to replace the spaces in your facet values with `gsub(' ', '%20', tech_facets$id)`.

Thanks for catching this and bringing it to our attention.

**Comment by mghoff** [comment]
@BeckerJoe 

Update: I've pushed several changes to the dev branch here. You should be able to install using `remotes::install_github()`, or by pulling the latest changes from dev and building from source.

Further, I found an additional issue with the EIA's API where it now wraps any bad request in an HTTP 500 error code that returns a JSON body containing the true HTTP error code (e.g. 400, 404, etc.). I will be reaching out to the API maintainers to see if this change was intentional to ensure that this current behavior is stable before merging to main and publishing this new patch version to CRAN.

**Comment by BeckerJoe** [comment]
Hey @mghoff,

I tried installing the new version using the following:

`install_github("ropensci/eia", ref = "dev")`

Still getting the same error unfortunately. I checked the changes on the dev branch, and I can see where you made the fix for the JSON wrapper issue and changed version numbers and all that, but I did not see the fix for this particular issue. Apologies if I am missing something simple here!

I also tried swapping out the spaces using `gsub(' ', '%20', tech_facets$id)` last night, but that end up throwing the following error.

`Error in eia_data(dir = "electricity/operating-generator-capacity", data = "nameplate-capacity-mw",  : 
  unused argument (technology = iter[[1, 2]])`

**Comment by mghoff** [comment]
@BeckerJoe 

The error you received is due to an incorrect calling of the `facets` function argument, where above you appear to have called `technology` as a directly named function argument to `eia_data()`. To correctly specify a facet, in this case "technology", it should be a named list component of the `facets` argument. See example below.

```
eia_data(
  dir = "electricity/operating-generator-capacity",
  data = "nameplate-capacity-mw",
  facets = list(technology = iter[[1, 2]])
)
```

**Comment by BeckerJoe** [comment]
@mghoff 
Ah, I see the dropped parenthesis now. Thank you!
